### ISSUE TITLE
APILatency is -1 within first few minutes of bot starting

### ISSUE THREAD

**Issue by backkslashh** [backkslashh/XTendu#1]
The title says it all. When running /ping, for APILatency, it will return -1. This only happens within the first few minutes.

Potential Solutions:
- Maybe this is a bug with discord. If so, handle this case and inform the user, it cannot return APILatency at this time.
- If this is a bug with my program, then figure out what is going wrong to make it return -1.

I leave this issue here on my own repository because I believe that this is a good first issue for beginners. If you'd like to work on this issue, please comment.

**Comment by geekananya** [comment]
Hi, I'd like to work on this issue.
